# Data parameters
test_size: 0.2

# Model parameters
early_stopping_rounds: 5
num_boost_round: 100
cv_folds: 5

# LGBM base parameters
lgbm_params:
  objective: 'regression'
  metric: 'rmse'
  boosting_type: 'gbdt'
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  verbose: 0

# Grid search parameters
param_grid:
  num_leaves: [16, 31, 64, 128]
  learning_rate: [0.01, 0.05, 0.1]
  max_depth: [-5, -1, 5, 10, 20]

# Technical indicators
technical_indicators:
  sma_window: 20
  ema_window: 12
  rsi_window: 14